#include "GammaService.h"
#include "Common.h"
#include <algorithm>
#include <cstdio>
#include <string>
#include <vector>

// ── Internal gamma write path ─────────────────────────────────────────────
// mscms!InternalSetDeviceGammaRamp writes the gamma at a layer the kernel
// does not reset on shell-flyout open (Action Center, Settings, UAC) — that
// reset is the visible flash — and bypasses the GdiIcmGammaRange registry
// cap so warm temperatures work without the HKLM tweak. Three-arg signature
// (hdc, ramp, dwReserved). Resolved from mscms.dll at startup; falls back to
// the public SetDeviceGammaRamp when the symbol is not exported.
typedef BOOL(WINAPI* InternalSetGammaFn)(HDC, LPVOID, DWORD);

static InternalSetGammaFn LoadInternalSetGamma()
{
    const wchar_t* dlls[] = { L"mscms.dll", L"gdi32.dll" };
    for (const wchar_t* dll : dlls)
    {
        HMODULE h = LoadLibraryW(dll);
        if (!h) continue;
        FARPROC p = GetProcAddress(h, "InternalSetDeviceGammaRamp");
        if (p) return reinterpret_cast<InternalSetGammaFn>(p);
    }
    return nullptr;
}

static const InternalSetGammaFn g_internalSetGamma = LoadInternalSetGamma();

// ── File logging (rotating, capped) ───────────────────────────────────────
static void Log(const std::string& msg)
{
    std::wstring dir = KnownFolder(FOLDERID_LocalAppData) + L"\\KelvinShift";
    CreateDirectoryW(dir.c_str(), nullptr);
    std::wstring path = dir + L"\\debug.log";

    const long long kMaxBytes = 256 * 1024;
    WIN32_FILE_ATTRIBUTE_DATA fad{};
    if (GetFileAttributesExW(path.c_str(), GetFileExInfoStandard, &fad))
    {
        long long size = ((long long)fad.nFileSizeHigh << 32) | fad.nFileSizeLow;
        if (size > kMaxBytes)
        {
            std::wstring rotated = path + L".old";
            DeleteFileW(rotated.c_str());
            MoveFileW(path.c_str(), rotated.c_str());
        }
    }

    HANDLE f = CreateFileW(path.c_str(), FILE_APPEND_DATA, FILE_SHARE_READ, nullptr,
                           OPEN_ALWAYS, FILE_ATTRIBUTE_NORMAL, nullptr);
    if (f == INVALID_HANDLE_VALUE) return;
    SYSTEMTIME t;
    GetLocalTime(&t);
    char line[512];
    int n = snprintf(line, sizeof(line), "%02d:%02d:%02d.%03d [gamma] %s\n",
                     t.wHour, t.wMinute, t.wSecond, t.wMilliseconds, msg.c_str());
    DWORD written;
    WriteFile(f, line, (DWORD)n, &written, nullptr);
    CloseHandle(f);
}

// ── Per-monitor enumeration ───────────────────────────────────────────────
// GetDC(NULL) returns a DC bound only to the primary display — on a multi-
// monitor desktop the secondary panel keeps its identity LUT (and on some
// driver permutations the call is rejected outright). We write per-device
// via CreateDCW(L"DISPLAY", deviceName) instead, the same pattern f.lux /
// DisplayCAL / Iris use.
static std::vector<std::wstring> EnumActiveDisplayDevices()
{
    std::vector<std::wstring> out;
    DISPLAY_DEVICEW dd{};
    dd.cb = sizeof(dd);
    for (DWORD i = 0; EnumDisplayDevicesW(nullptr, i, &dd, 0); ++i)
    {
        if ((dd.StateFlags & DISPLAY_DEVICE_ATTACHED_TO_DESKTOP) &&
            !(dd.StateFlags & DISPLAY_DEVICE_MIRRORING_DRIVER))
        {
            out.emplace_back(dd.DeviceName);
        }
        dd.cb = sizeof(dd);
    }
    return out;
}

// ── Blackbody table (Planck + CIE 1931 + IEC sRGB) ────────────────────────
// Generated by tools/generate_blackbody_table.py from primary public-domain
// sources: Planck's law (physics), CIE 1931 2° standard observer color
// matching functions, sRGB linear transform (IEC 61966-2-1), chromaticity-
// preserving uniform gamut fit, sRGB OETF for the display LUT. 6500K is the
// D65 identity (1, 1, 1). 91 entries, 100K steps, 1000K → 10000K.
namespace {
struct Entry { float r, g, b; };
const Entry kBlackbody[] = {
    {1.00000000f, 0.09497672f, 0.00000000f}, // 1000K
    {1.00000000f, 0.20572527f, 0.00000000f}, // 1100K
    {1.00000000f, 0.27422893f, 0.00000000f}, // 1200K
    {1.00000000f, 0.32761182f, 0.00000000f}, // 1300K
    {1.00000000f, 0.37245445f, 0.00000000f}, // 1400K
    {1.00000000f, 0.41157160f, 0.00000000f}, // 1500K
    {1.00000000f, 0.44647490f, 0.00000000f}, // 1600K
    {1.00000000f, 0.47808956f, 0.00000000f}, // 1700K
    {1.00000000f, 0.50703295f, 0.00000000f}, // 1800K
    {1.00000000f, 0.53374308f, 0.00016018f}, // 1900K
    {1.00000000f, 0.55854535f, 0.08767389f}, // 2000K
    {1.00000000f, 0.58169029f, 0.14153195f}, // 2100K
    {1.00000000f, 0.60337628f, 0.18456294f}, // 2200K
    {1.00000000f, 0.62376407f, 0.22238807f}, // 2300K
    {1.00000000f, 0.64298639f, 0.25700254f}, // 2400K
    {1.00000000f, 0.66115460f, 0.28935470f}, // 2500K
    {1.00000000f, 0.67836336f, 0.31997043f}, // 2600K
    {1.00000000f, 0.69469405f, 0.34917182f}, // 2700K
    {1.00000000f, 0.71021737f, 0.37717090f}, // 2800K
    {1.00000000f, 0.72499523f, 0.40411533f}, // 2900K
    {1.00000000f, 0.73908226f, 0.43011283f}, // 3000K
    {1.00000000f, 0.75252702f, 0.45524518f}, // 3100K
    {1.00000000f, 0.76537290f, 0.47957663f}, // 3200K
    {1.00000000f, 0.77765890f, 0.50315920f}, // 3300K
    {1.00000000f, 0.78942024f, 0.52603617f}, // 3400K
    {1.00000000f, 0.80068889f, 0.54824437f}, // 3500K
    {1.00000000f, 0.81149394f, 0.56981579f}, // 3600K
    {1.00000000f, 0.82186201f, 0.59077867f}, // 3700K
    {1.00000000f, 0.83181753f, 0.61115838f}, // 3800K
    {1.00000000f, 0.84138298f, 0.63097792f}, // 3900K
    {1.00000000f, 0.85057911f, 0.65025842f}, // 4000K
    {1.00000000f, 0.85942515f, 0.66901945f}, // 4100K
    {1.00000000f, 0.86793892f, 0.68727926f}, // 4200K
    {1.00000000f, 0.87613703f, 0.70505498f}, // 4300K
    {1.00000000f, 0.88403494f, 0.72236280f}, // 4400K
    {1.00000000f, 0.89164712f, 0.73921803f}, // 4500K
    {1.00000000f, 0.89898710f, 0.75563526f}, // 4600K
    {1.00000000f, 0.90606758f, 0.77162841f}, // 4700K
    {1.00000000f, 0.91290047f, 0.78721079f}, // 4800K
    {1.00000000f, 0.91949700f, 0.80239517f}, // 4900K
    {1.00000000f, 0.92586772f, 0.81719380f}, // 5000K
    {1.00000000f, 0.93202261f, 0.83161847f}, // 5100K
    {1.00000000f, 0.93797107f, 0.84568055f}, // 5200K
    {1.00000000f, 0.94372201f, 0.85939098f}, // 5300K
    {1.00000000f, 0.94928384f, 0.87276032f}, // 5400K
    {1.00000000f, 0.95466454f, 0.88579876f}, // 5500K
    {1.00000000f, 0.95987167f, 0.89851618f}, // 5600K
    {1.00000000f, 0.96491242f, 0.91092208f}, // 5700K
    {1.00000000f, 0.96979359f, 0.92302568f}, // 5800K
    {1.00000000f, 0.97452166f, 0.93483589f}, // 5900K
    {1.00000000f, 0.97910280f, 0.94636134f}, // 6000K
    {1.00000000f, 0.98354285f, 0.95761036f}, // 6100K
    {1.00000000f, 0.98784741f, 0.96859104f}, // 6200K
    {1.00000000f, 0.99202178f, 0.97931120f}, // 6300K
    {1.00000000f, 0.99607104f, 0.98977841f}, // 6400K
    {1.00000000f, 1.00000000f, 1.00000000f}, // 6500K (D65)
    {0.99011050f, 0.99388804f, 1.00000000f}, // 6600K
    {0.98062785f, 0.98800513f, 1.00000000f}, // 6700K
    {0.97152868f, 0.98233903f, 1.00000000f}, // 6800K
    {0.96279135f, 0.97687837f, 1.00000000f}, // 6900K
    {0.95439578f, 0.97161254f, 1.00000000f}, // 7000K
    {0.94632332f, 0.96653165f, 1.00000000f}, // 7100K
    {0.93855662f, 0.96162646f, 1.00000000f}, // 7200K
    {0.93107952f, 0.95688836f, 1.00000000f}, // 7300K
    {0.92387694f, 0.95230926f, 1.00000000f}, // 7400K
    {0.91693484f, 0.94788158f, 1.00000000f}, // 7500K
    {0.91024006f, 0.94359824f, 1.00000000f}, // 7600K
    {0.90378030f, 0.93945255f, 1.00000000f}, // 7700K
    {0.89754405f, 0.93543826f, 1.00000000f}, // 7800K
    {0.89152051f, 0.93154946f, 1.00000000f}, // 7900K
    {0.88569955f, 0.92778060f, 1.00000000f}, // 8000K
    {0.88007165f, 0.92412643f, 1.00000000f}, // 8100K
    {0.87462788f, 0.92058204f, 1.00000000f}, // 8200K
    {0.86935980f, 0.91714274f, 1.00000000f}, // 8300K
    {0.86425950f, 0.91380412f, 1.00000000f}, // 8400K
    {0.85931951f, 0.91056203f, 1.00000000f}, // 8500K
    {0.85453277f, 0.90741252f, 1.00000000f}, // 8600K
    {0.84989264f, 0.90435184f, 1.00000000f}, // 8700K
    {0.84539283f, 0.90137645f, 1.00000000f}, // 8800K
    {0.84102741f, 0.89848300f, 1.00000000f}, // 8900K
    {0.83679075f, 0.89566829f, 1.00000000f}, // 9000K
    {0.83267753f, 0.89292930f, 1.00000000f}, // 9100K
    {0.82868271f, 0.89026314f, 1.00000000f}, // 9200K
    {0.82480152f, 0.88766708f, 1.00000000f}, // 9300K
    {0.82102942f, 0.88513851f, 1.00000000f}, // 9400K
    {0.81736210f, 0.88267494f, 1.00000000f}, // 9500K
    {0.81379549f, 0.88027403f, 1.00000000f}, // 9600K
    {0.81032570f, 0.87793350f, 1.00000000f}, // 9700K
    {0.80694904f, 0.87565123f, 1.00000000f}, // 9800K
    {0.80366200f, 0.87342514f, 1.00000000f}, // 9900K
    {0.80046123f, 0.87125329f, 1.00000000f}, // 10000K
};
const int kBlackbodyCount = (int)(sizeof(kBlackbody) / sizeof(kBlackbody[0]));
} // namespace

GammaService::Rgb GammaService::KelvinToRgb(int kelvin)
{
    int k = std::clamp(kelvin, 1000, 10000);
    int index = (k - 1000) / 100;
    float alpha = (float)((k - 1000) % 100) / 100.0f;

    if (index >= kBlackbodyCount - 1)
    {
        const Entry& e = kBlackbody[kBlackbodyCount - 1];
        return { e.r, e.g, e.b };
    }
    const Entry& lo = kBlackbody[index];
    const Entry& hi = kBlackbody[index + 1];
    return {
        lo.r + alpha * (hi.r - lo.r),
        lo.g + alpha * (hi.g - lo.g),
        lo.b + alpha * (hi.b - lo.b),
    };
}

// ── Public API ────────────────────────────────────────────────────────────

bool GammaService::ApplyKelvinWithBrightness(int kelvin, double brightness)
{
    int k = std::clamp(kelvin, 1000, 10000);
    double b = std::clamp(brightness, 0.1, 1.0);
    if (hasApplied_ && k == currentKelvin_ && fabs(b - currentBrightness_) < 0.001)
        return true;
    currentKelvin_ = k;
    currentBrightness_ = b;
    Rgb rgb = KelvinToRgb(k);
    {
        std::lock_guard<std::mutex> lock(writeLock_);
        BuildRamp(rgb.r * (float)b, rgb.g * (float)b, rgb.b * (float)b);
        WriteRamp();
    }
    hasApplied_ = true;
    return true;
}

bool GammaService::Reapply()
{
    if (!hasApplied_) return true;
    std::lock_guard<std::mutex> lock(writeLock_);
    if (!GammaMatchesExpected())
        WriteRamp();
    return true;
}

void GammaService::Reset()
{
    currentKelvin_ = 6500;
    currentBrightness_ = 1.0;
    hasApplied_ = false;
    std::lock_guard<std::mutex> lock(writeLock_);
    BuildRamp(1.0f, 1.0f, 1.0f);
    WriteRamp();
}

// ── Ramp construction / write ─────────────────────────────────────────────

void GammaService::BuildRamp(float r, float g, float b)
{
    // Stable ramp — no per-write perturbation. The read-back gate in Reapply
    // already ensures identical successive writes never happen at our layer.
    for (int i = 0; i < 256; ++i)
    {
        float t = i / 255.0f;
        ramp_[i]       = (WORD)std::clamp((int)(t * r * 65535.0f), 0, 65535);
        ramp_[i + 256] = (WORD)std::clamp((int)(t * g * 65535.0f), 0, 65535);
        ramp_[i + 512] = (WORD)std::clamp((int)(t * b * 65535.0f), 0, 65535);
    }
}

bool GammaService::GammaMatchesExpected()
{
    auto devices = EnumActiveDisplayDevices();
    if (devices.empty()) return true; // assume OK rather than spam writes

    // Drift on any monitor means we need to re-write everywhere. Sample the
    // channel mid-points — catches the identity reset (mid = 0x8000) cheaply.
    const int tol = 256;
    for (const auto& name : devices)
    {
        HDC hdc = CreateDCW(L"DISPLAY", name.c_str(), nullptr, nullptr);
        if (!hdc) continue;
        BOOL ok = GetDeviceGammaRamp(hdc, probeBuffer_);
        DeleteDC(hdc);
        if (!ok) continue;

        if (abs(probeBuffer_[128] - ramp_[128]) > tol
         || abs(probeBuffer_[256 + 128] - ramp_[256 + 128]) > tol
         || abs(probeBuffer_[512 + 128] - ramp_[512 + 128]) > tol)
            return false;
    }
    return true;
}

bool GammaService::WriteRamp()
{
    auto devices = EnumActiveDisplayDevices();

    // Defensive fallback: if enumeration ever returns nothing, write to the
    // primary-screen DC so we at least light up one monitor.
    if (devices.empty())
    {
        HDC hdc = GetDC(nullptr);
        if (!hdc) { Log("GetDC(NULL) returned 0 and EnumDisplayDevices empty"); return false; }
        bool ok = false;
        for (int attempt = 0; attempt < 3 && !ok; ++attempt)
            ok = g_internalSetGamma
                ? (g_internalSetGamma(hdc, ramp_, 0) != FALSE)
                : (SetDeviceGammaRamp(hdc, ramp_) != FALSE);
        ReleaseDC(nullptr, hdc);
        return ok;
    }

    // Write to every attached monitor via its own CreateDC'd HDC. The old
    // GetDC(NULL) path only touched the primary display on multi-monitor
    // configs; the secondary panel stayed at identity.
    int writtenCount = 0;
    DWORD lastErr = 0;
    for (const auto& name : devices)
    {
        HDC hdc = CreateDCW(L"DISPLAY", name.c_str(), nullptr, nullptr);
        if (!hdc) { lastErr = GetLastError(); continue; }

        // Some drivers fail the first call but succeed on the second. Prefer
        // the kernel path; fall back to the documented one if Internal* is missing.
        bool ok = false;
        for (int attempt = 0; attempt < 3 && !ok; ++attempt)
        {
            ok = g_internalSetGamma
                ? (g_internalSetGamma(hdc, ramp_, 0) != FALSE)
                : (SetDeviceGammaRamp(hdc, ramp_) != FALSE);
        }
        if (ok) ++writtenCount;
        else    lastErr = GetLastError();

        DeleteDC(hdc); // CreateDC pairs with DeleteDC, not ReleaseDC.
    }

    if (writtenCount == 0)
    {
        char buf[200];
        snprintf(buf, sizeof(buf),
                 "gamma write failed across all %d display(s) (last err=%lu, path=%s)",
                 (int)devices.size(), lastErr,
                 g_internalSetGamma ? "internal" : "public");
        Log(buf);
    }
    else if (!loggedFirstSuccess_)
    {
        char buf[240];
        snprintf(buf, sizeof(buf),
                 "%s OK on %d/%d display(s) rampSample=[R0=%u R128=%u R255=%u G128=%u B128=%u]",
                 g_internalSetGamma ? "InternalSetDeviceGammaRamp" : "SetDeviceGammaRamp",
                 writtenCount, (int)devices.size(),
                 ramp_[0], ramp_[128], ramp_[255], ramp_[256 + 128], ramp_[512 + 128]);
        Log(buf);
        loggedFirstSuccess_ = true;
    }

    return writtenCount > 0;
}
