// KelvinShift – GammaController.swift
//
// Direct gamma table manipulation for accurate color temperature control.
// Uses CoreGraphics CGSetDisplayTransferByTable.
//
// Blackbody RGB table is computed from primary public-domain sources:
// Planck's law (physics), the CIE 1931 2° standard observer color matching
// functions (CIE 1931), and the sRGB linear transform (IEC 61966-2-1).
// Full derivation in tools/generate_blackbody_table.py.

import AppKit
import Foundation
import CoreGraphics

final class GammaController {

    static let shared = GammaController()

    /// Blackbody color lookup table: RGB values at 100K intervals from 1000K to 10000K.
    /// Generated by tools/generate_blackbody_table.py — Planck's law integrated
    /// against the CIE 1931 2° standard observer color matching functions,
    /// mapped through the sRGB linear transform (IEC 61966-2-1), gamut-fitted
    /// by chromaticity-preserving uniform scaling, and encoded with the sRGB
    /// OETF for the display LUT. 6500K is the D65 identity (1, 1, 1).
    private static let blackbodyTable: [(r: Float, g: Float, b: Float)] = [
        (1.00000000, 0.09497672, 0.00000000), // 1000K
        (1.00000000, 0.20572527, 0.00000000), // 1100K
        (1.00000000, 0.27422893, 0.00000000), // 1200K
        (1.00000000, 0.32761182, 0.00000000), // 1300K
        (1.00000000, 0.37245445, 0.00000000), // 1400K
        (1.00000000, 0.41157160, 0.00000000), // 1500K
        (1.00000000, 0.44647490, 0.00000000), // 1600K
        (1.00000000, 0.47808956, 0.00000000), // 1700K
        (1.00000000, 0.50703295, 0.00000000), // 1800K
        (1.00000000, 0.53374308, 0.00016018), // 1900K
        (1.00000000, 0.55854535, 0.08767389), // 2000K
        (1.00000000, 0.58169029, 0.14153195), // 2100K
        (1.00000000, 0.60337628, 0.18456294), // 2200K
        (1.00000000, 0.62376407, 0.22238807), // 2300K
        (1.00000000, 0.64298639, 0.25700254), // 2400K
        (1.00000000, 0.66115460, 0.28935470), // 2500K
        (1.00000000, 0.67836336, 0.31997043), // 2600K
        (1.00000000, 0.69469405, 0.34917182), // 2700K
        (1.00000000, 0.71021737, 0.37717090), // 2800K
        (1.00000000, 0.72499523, 0.40411533), // 2900K
        (1.00000000, 0.73908226, 0.43011283), // 3000K
        (1.00000000, 0.75252702, 0.45524518), // 3100K
        (1.00000000, 0.76537290, 0.47957663), // 3200K
        (1.00000000, 0.77765890, 0.50315920), // 3300K
        (1.00000000, 0.78942024, 0.52603617), // 3400K
        (1.00000000, 0.80068889, 0.54824437), // 3500K
        (1.00000000, 0.81149394, 0.56981579), // 3600K
        (1.00000000, 0.82186201, 0.59077867), // 3700K
        (1.00000000, 0.83181753, 0.61115838), // 3800K
        (1.00000000, 0.84138298, 0.63097792), // 3900K
        (1.00000000, 0.85057911, 0.65025842), // 4000K
        (1.00000000, 0.85942515, 0.66901945), // 4100K
        (1.00000000, 0.86793892, 0.68727926), // 4200K
        (1.00000000, 0.87613703, 0.70505498), // 4300K
        (1.00000000, 0.88403494, 0.72236280), // 4400K
        (1.00000000, 0.89164712, 0.73921803), // 4500K
        (1.00000000, 0.89898710, 0.75563526), // 4600K
        (1.00000000, 0.90606758, 0.77162841), // 4700K
        (1.00000000, 0.91290047, 0.78721079), // 4800K
        (1.00000000, 0.91949700, 0.80239517), // 4900K
        (1.00000000, 0.92586772, 0.81719380), // 5000K
        (1.00000000, 0.93202261, 0.83161847), // 5100K
        (1.00000000, 0.93797107, 0.84568055), // 5200K
        (1.00000000, 0.94372201, 0.85939098), // 5300K
        (1.00000000, 0.94928384, 0.87276032), // 5400K
        (1.00000000, 0.95466454, 0.88579876), // 5500K
        (1.00000000, 0.95987167, 0.89851618), // 5600K
        (1.00000000, 0.96491242, 0.91092208), // 5700K
        (1.00000000, 0.96979359, 0.92302568), // 5800K
        (1.00000000, 0.97452166, 0.93483589), // 5900K
        (1.00000000, 0.97910280, 0.94636134), // 6000K
        (1.00000000, 0.98354285, 0.95761036), // 6100K
        (1.00000000, 0.98784741, 0.96859104), // 6200K
        (1.00000000, 0.99202178, 0.97931120), // 6300K
        (1.00000000, 0.99607104, 0.98977841), // 6400K
        (1.00000000, 1.00000000, 1.00000000), // 6500K (D65)
        (0.99011050, 0.99388804, 1.00000000), // 6600K
        (0.98062785, 0.98800513, 1.00000000), // 6700K
        (0.97152868, 0.98233903, 1.00000000), // 6800K
        (0.96279135, 0.97687837, 1.00000000), // 6900K
        (0.95439578, 0.97161254, 1.00000000), // 7000K
        (0.94632332, 0.96653165, 1.00000000), // 7100K
        (0.93855662, 0.96162646, 1.00000000), // 7200K
        (0.93107952, 0.95688836, 1.00000000), // 7300K
        (0.92387694, 0.95230926, 1.00000000), // 7400K
        (0.91693484, 0.94788158, 1.00000000), // 7500K
        (0.91024006, 0.94359824, 1.00000000), // 7600K
        (0.90378030, 0.93945255, 1.00000000), // 7700K
        (0.89754405, 0.93543826, 1.00000000), // 7800K
        (0.89152051, 0.93154946, 1.00000000), // 7900K
        (0.88569955, 0.92778060, 1.00000000), // 8000K
        (0.88007165, 0.92412643, 1.00000000), // 8100K
        (0.87462788, 0.92058204, 1.00000000), // 8200K
        (0.86935980, 0.91714274, 1.00000000), // 8300K
        (0.86425950, 0.91380412, 1.00000000), // 8400K
        (0.85931951, 0.91056203, 1.00000000), // 8500K
        (0.85453277, 0.90741252, 1.00000000), // 8600K
        (0.84989264, 0.90435184, 1.00000000), // 8700K
        (0.84539283, 0.90137645, 1.00000000), // 8800K
        (0.84102741, 0.89848300, 1.00000000), // 8900K
        (0.83679075, 0.89566829, 1.00000000), // 9000K
        (0.83267753, 0.89292930, 1.00000000), // 9100K
        (0.82868271, 0.89026314, 1.00000000), // 9200K
        (0.82480152, 0.88766708, 1.00000000), // 9300K
        (0.82102942, 0.88513851, 1.00000000), // 9400K
        (0.81736210, 0.88267494, 1.00000000), // 9500K
        (0.81379549, 0.88027403, 1.00000000), // 9600K
        (0.81032570, 0.87793350, 1.00000000), // 9700K
        (0.80694904, 0.87565123, 1.00000000), // 9800K
        (0.80366200, 0.87342514, 1.00000000), // 9900K
        (0.80046123, 0.87125329, 1.00000000), // 10000K
    ]

    private var savedGammaRamps: [CGDirectDisplayID: (r: [CGGammaValue], g: [CGGammaValue], b: [CGGammaValue])] = [:]
    private var currentKelvin: Int = 6500
    private var currentBrightness: Double = 1.0
    private var hasAppliedGamma: Bool = false

    /// Displays the current ramp has actually been written to. Compared against
    /// the live online-display list so a monitor that appeared since the last
    /// write can't be swallowed by the redundant-write gate below.
    private var appliedDisplayIDs: Set<CGDirectDisplayID> = []

    /// Pending post-reconfiguration re-asserts (see scheduleReapplyAfterDisplayChange).
    private var pendingReapplies: [DispatchWorkItem] = []

    private init() {
        saveOriginalGamma()
        observeDisplayReconfiguration()
    }

    // MARK: - Public API

    /// Apply a color temperature to all displays.
    /// - Parameter kelvin: Color temperature in Kelvin (1000-10000)
    @discardableResult
    func applyKelvin(_ kelvin: Int) -> Bool {
        return applyKelvinWithBrightness(kelvin, brightness: 1.0)
    }

    /// Apply a color temperature with brightness adjustment to all displays.
    /// - Parameters:
    ///   - kelvin: Color temperature in Kelvin (1000-10000)
    ///   - brightness: Brightness multiplier (0.1-1.0, where 1.0 is full brightness)
    @discardableResult
    func applyKelvinWithBrightness(_ kelvin: Int, brightness: Double) -> Bool {
        let clampedKelvin = max(1000, min(10000, kelvin))
        let clampedBrightness = max(0.1, min(1.0, brightness))

        // Skip redundant gamma-table writes. Each CGSetDisplayTransferByTable call
        // causes Chromium 148+ on macOS 26.4 to re-query the display color profile,
        // producing a visible flash. Only re-apply when the target actually changes.
        // The display set is part of the gate: docking adds a monitor without
        // changing the target Kelvin, and a value-only check would skip it
        // forever (until something else forced a write — which is why toggling
        // KelvinShift off and on used to "fix" a freshly docked screen).
        if hasAppliedGamma
            && clampedKelvin == currentKelvin
            && abs(clampedBrightness - currentBrightness) < 0.001
            && appliedDisplayIDs == Set(getDisplayIDs()) {
            return true
        }

        currentKelvin = clampedKelvin
        currentBrightness = clampedBrightness

        let rgb = Self.kelvinToRGB(clampedKelvin)
        let ok = applyRGBMultipliers(r: rgb.r, g: rgb.g, b: rgb.b, brightness: Float(clampedBrightness))
        if ok { hasAppliedGamma = true }
        return ok
    }

    /// Get the current applied color temperature.
    func getCurrentKelvin() -> Int {
        return currentKelvin
    }

    /// Get the current applied brightness.
    func getCurrentBrightness() -> Double {
        return currentBrightness
    }

    /// Reset gamma to original values (6500K equivalent).
    func resetGamma() {
        cancelPendingReapplies()
        currentKelvin = 6500
        currentBrightness = 1.0
        hasAppliedGamma = false
        appliedDisplayIDs = []
        CGDisplayRestoreColorSyncSettings()
    }

    // MARK: - Display Reconfiguration

    /// Docking, undocking, display mode changes, and wake all reprogram the
    /// hardware LUT behind our back — sometimes only on the arriving monitor,
    /// sometimes on every one of them. The schedule tick can't recover on its
    /// own because the target Kelvin hasn't changed, so re-assert the ramp
    /// whenever the display configuration moves. (Same shape as the Windows
    /// GammaWatchdog: react to the event, then let a read-back decide whether a
    /// write is actually needed.)
    private func observeDisplayReconfiguration() {
        NotificationCenter.default.addObserver(
            forName: NSApplication.didChangeScreenParametersNotification,
            object: nil, queue: .main
        ) { [weak self] _ in
            self?.scheduleReapplyAfterDisplayChange()
        }

        NSWorkspace.shared.notificationCenter.addObserver(
            forName: NSWorkspace.didWakeNotification,
            object: nil, queue: .main
        ) { [weak self] _ in
            self?.scheduleReapplyAfterDisplayChange()
        }
    }

    /// A dock handshake emits a burst of screen-parameter notifications, and the
    /// arriving panel is not necessarily ready to accept a gamma table when the
    /// first one lands. Coalesce the burst, then re-assert on a short ladder.
    /// Every attempt is read-back gated, so once the ramp takes, the remaining
    /// attempts write nothing.
    private static let reapplyDelays: [TimeInterval] = [0.4, 1.5, 4.0]

    private func scheduleReapplyAfterDisplayChange() {
        cancelPendingReapplies()
        pendingReapplies = Self.reapplyDelays.map { delay in
            let item = DispatchWorkItem { [weak self] in self?.reassertCurrentRamp() }
            DispatchQueue.main.asyncAfter(deadline: .now() + delay, execute: item)
            return item
        }
    }

    private func cancelPendingReapplies() {
        pendingReapplies.forEach { $0.cancel() }
        pendingReapplies = []
    }

    /// Re-write the current Kelvin/brightness to every online display, bypassing
    /// the value cache. A no-op on displays that still hold the right ramp.
    private func reassertCurrentRamp() {
        // Nothing of ours is on screen (app disabled, or reset) — leave the
        // displays with whatever ColorSync gave them.
        guard hasAppliedGamma else { return }
        let rgb = Self.kelvinToRGB(currentKelvin)
        _ = applyRGBMultipliers(r: rgb.r, g: rgb.g, b: rgb.b, brightness: Float(currentBrightness))
    }

    // MARK: - Color Temperature Conversion

    /// Convert Kelvin to RGB multipliers using blackbody lookup table with interpolation.
    static func kelvinToRGB(_ kelvin: Int) -> (r: Float, g: Float, b: Float) {
        let clamped = max(1000, min(10000, kelvin))

        // Calculate table index and interpolation factor
        let index = (clamped - 1000) / 100
        let alpha = Float((clamped - 1000) % 100) / 100.0

        // Handle edge case at 10000K
        if index >= blackbodyTable.count - 1 {
            return blackbodyTable[blackbodyTable.count - 1]
        }

        // Linear interpolation between two table entries
        let low = blackbodyTable[index]
        let high = blackbodyTable[index + 1]

        return (
            r: low.r + alpha * (high.r - low.r),
            g: low.g + alpha * (high.g - low.g),
            b: low.b + alpha * (high.b - low.b)
        )
    }

    // MARK: - Gamma Table Manipulation

    private func getDisplayIDs() -> [CGDirectDisplayID] {
        var displayCount: UInt32 = 0
        CGGetOnlineDisplayList(0, nil, &displayCount)

        var displays = [CGDirectDisplayID](repeating: 0, count: Int(displayCount))
        CGGetOnlineDisplayList(displayCount, &displays, &displayCount)

        return displays
    }

    private func saveOriginalGamma() {
        for displayID in getDisplayIDs() {
            let capacity = CGDisplayGammaTableCapacity(displayID)
            var sampleCount: UInt32 = 0

            var redTable = [CGGammaValue](repeating: 0, count: Int(capacity))
            var greenTable = [CGGammaValue](repeating: 0, count: Int(capacity))
            var blueTable = [CGGammaValue](repeating: 0, count: Int(capacity))

            let result = CGGetDisplayTransferByTable(
                displayID,
                capacity,
                &redTable,
                &greenTable,
                &blueTable,
                &sampleCount
            )

            if result == .success {
                savedGammaRamps[displayID] = (
                    r: Array(redTable.prefix(Int(sampleCount))),
                    g: Array(greenTable.prefix(Int(sampleCount))),
                    b: Array(blueTable.prefix(Int(sampleCount)))
                )
            }
        }
    }

    private func applyRGBMultipliers(r: Float, g: Float, b: Float, brightness: Float = 1.0) -> Bool {
        var success = true
        var written: Set<CGDirectDisplayID> = []

        for displayID in getDisplayIDs() {
            let capacity = CGDisplayGammaTableCapacity(displayID)
            let count = Int(capacity)

            // A display still mid-handshake can report a degenerate capacity,
            // and the ramp math below divides by count - 1. Skipping it also
            // keeps it out of `written`, so the display-set gate retries on the
            // next tick instead of writing NaNs now.
            guard count > 1 else { continue }

            // Create linear ramps scaled by the RGB multipliers and brightness
            var redTable = [CGGammaValue](repeating: 0, count: count)
            var greenTable = [CGGammaValue](repeating: 0, count: count)
            var blueTable = [CGGammaValue](repeating: 0, count: count)

            for i in 0..<count {
                let value = CGGammaValue(i) / CGGammaValue(count - 1)
                redTable[i] = value * CGGammaValue(r) * CGGammaValue(brightness)
                greenTable[i] = value * CGGammaValue(g) * CGGammaValue(brightness)
                blueTable[i] = value * CGGammaValue(b) * CGGammaValue(brightness)
            }

            written.insert(displayID)

            // Every LUT write is a visible display update, so skip the displays
            // already holding the ramp we were about to write. This is what
            // makes the post-dock retry ladder free.
            if rampMatches(displayID, redTable, greenTable, blueTable) { continue }

            let result = CGSetDisplayTransferByTable(
                displayID,
                UInt32(count),
                redTable,
                greenTable,
                blueTable
            )

            if result != .success {
                NSLog("[KelvinShift] Failed to set gamma for display \(displayID)")
                written.remove(displayID)
                success = false
            }
        }

        appliedDisplayIDs = written
        return success
    }

    /// True when the display's current transfer table already matches the one we
    /// are about to write. Compared with a tolerance: the hardware LUT quantizes
    /// on the way in, so a read-back never comes back bit-exact.
    private func rampMatches(
        _ displayID: CGDirectDisplayID,
        _ red: [CGGammaValue],
        _ green: [CGGammaValue],
        _ blue: [CGGammaValue]
    ) -> Bool {
        let count = red.count
        var sampleCount: UInt32 = 0
        var currentRed = [CGGammaValue](repeating: 0, count: count)
        var currentGreen = [CGGammaValue](repeating: 0, count: count)
        var currentBlue = [CGGammaValue](repeating: 0, count: count)

        let result = CGGetDisplayTransferByTable(
            displayID,
            UInt32(count),
            &currentRed,
            &currentGreen,
            &currentBlue,
            &sampleCount
        )
        guard result == .success, Int(sampleCount) == count else { return false }

        let tolerance: CGGammaValue = 1.0 / 256.0
        for i in 0..<count {
            if abs(currentRed[i]   - red[i])   > tolerance { return false }
            if abs(currentGreen[i] - green[i]) > tolerance { return false }
            if abs(currentBlue[i]  - blue[i])  > tolerance { return false }
        }
        return true
    }
}
